parameters:
    fos_twitter.api.class: PROCERGS\Generic\TwitterOAuthProxiedBundle\Service\TwitterOAuth

services:
    kernel.listener.twitterLibProxy:
        class: PROCERGS\Generic\TwitterOAuthProxiedBundle\EventListener\RequestListener
        arguments:
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
