sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

addons:
  postgresql: "9.3"

services:
  - memcached

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - psql -c "create user logincidadao with password '';" -U postgres
  - psql -c "create database logincidadao with owner logincidadao" -U postgres
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer install --prefer-dist
  - chmod -R 777 app/cache app/logs web/uploads
  - echo y | php app/console doctrine:schema:update --force
  - echo y | php app/console doctrine:schema:update --em=logs --force
  - echo y | php app/console lc:database:populate batch/

script:
  - ./bin/phpunit -c app --coverage-clover=clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
