# API
procergs_login_cidadao_api_core:
    resource: "@PROCERGSLoginCidadaoAPIBundle/Controller"
    defaults: { _format: json }
    type:     annotation
    prefix:   /

procergs_login_cidadao_Notification:
    type: rest
    prefix: /
    resource: "@PROCERGSLoginCidadaoAPIBundle/Controller/NotificationController.php"
