parameters:
    lc_api_access_token_definer.class: PROCERGS\LoginCidadao\APIBundle\Event\LoggedInUserListener

services:
    lc.api.logged_in_user_listener:
        class: %lc_api_access_token_definer.class%
        arguments: [ "@doctrine.orm.entity_manager", "@security.context", "@simplethings_entityaudit.config" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
