imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        fos_csrf_provider: "@form.csrf_provider"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ "PROCERGSLoginCidadaoCoreBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    delivery_address: %mailer_sender_mail%

fos_oauth_server:
  db_driver: orm
  client_class:         PROCERGS\OAuthBundle\Entity\Client
  access_token_class:   PROCERGS\OAuthBundle\Entity\AccessToken
  refresh_token_class:  PROCERGS\OAuthBundle\Entity\RefreshToken
  auth_code_class:      PROCERGS\OAuthBundle\Entity\AuthCode
  service:
      user_provider: fos_user.user_manager
      options:
          supported_scopes: username name cpf birthdate email city

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: PROCERGS\LoginCidadao\CoreBundle\Entity\Person
    registration:
        confirmation:
            enabled: true
            from_email:
              address: noreply@%site_domain%
              sender_name: %site_domain%
        form:
            type: procergs_person_registration
    profile:
        form:
            type: procergs_person_profile

# Audit Trail
simple_things_entity_audit:
    audited_entities:
        - PROCERGS\LoginCidadao\CoreBundle\Entity\Authorization
        - PROCERGS\LoginCidadao\CoreBundle\Entity\City
        - PROCERGS\LoginCidadao\CoreBundle\Entity\Person
        - PROCERGS\OAuthBundle\Entity\AccessToken
        - PROCERGS\OAuthBundle\Entity\AuthCode
        - PROCERGS\OAuthBundle\Entity\Client
        - PROCERGS\OAuthBundle\Entity\RefreshToken

fos_facebook:
    alias:  facebook
    app_id: %facebook_app_id%
    secret: %facebook_app_secret%
    cookie: true
    permissions: [email, user_about_me, user_birthday, user_location]

hwi_oauth:
    connect:
        account_connector: procergs.hwi_twitter.user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            twitter: twitterId
    resource_owners:
        twitter:
            type:           twitter
            client_id:      %twitter_app_key%
            client_secret:  %twitter_app_secret%
            scope:          "email"
parameters:
    buzz.client.class: PROCERGS\Generic\HWIOAuthProxyBundle\Buzz\Client\CurlProxy
