procergs_generic_locale:
    resource: "@PROCERGSGenericLocaleBundle/Controller/"
    type:     annotation
    prefix:   /locale

procergs_login_cidadao_ui:
    resource: "@PROCERGSLoginCidadaoUIBundle/Controller/"
    type:     annotation
    prefix:   /

procergs_login_cidadao_core:
    resource: "@PROCERGSLoginCidadaoCoreBundle/Controller"
    type:     annotation
    prefix:   /api/v1

procergso_auth:
    resource: "@PROCERGSOAuthBundle/Resources/config/routing.yml"
    prefix:   /auth

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

# UserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile