services:
    sms.config:
        class: PROCERGS\Sms\Model\SmsServiceConfiguration
        arguments:
            - "%procergs.sms.uri.send%"
            - "%procergs.sms.uri.receive%"
            - "%procergs.sms.uri.status%"
            - "%procergs.sms.system.id%"
            - "%procergs.sms.system.key%"
            - "%procergs.sms.service_order%"
            - "%procergs.sms.from.prefix%"
            - "%procergs.sms.should_send%"
        lazy: true

    sms:
        class: PROCERGS\Sms\SmsService
        arguments:
            - "@circle.restclient"
            - "@sms.config"
        lazy: true
