parameters:
#    procergs_login_cidadao_core.example.class: PROCERGS\LoginCidadao\CoreBundle\Example

services:
    procergs_person.registration.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_registration }
#    procergs_login_cidadao_core.example:
#        class: %procergs_login_cidadao_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
