parameters:
    security.authentication.success_handler.class: PROCERGS\LoginCidadao\CoreBundle\Handler\AuthenticationSuccessHandler
    fos_facebook.user.login.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\FacebookProvider
    procergs.hwi_twitter.user_provider.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\FOSUBUserProvider
    procergs_person.registration.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\RegistrationFormType
    procergs_person.profile.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ProfileFormType
    procergs_person.resetting.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ResettingFormType
    procergs_logincidadao.user_provider.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\LoginCidadaoProvider
    procergs_logincidadao.user_manager.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Manager\UserManager
    

services:
    security.authentication.success_handler:
        class: %security.authentication.success_handler.class%
        public: false
        arguments: ["@router", "@doctrine.orm.entity_manager", "@doctrine.orm.entity_manager", "@session"]

    fos_facebook.user.login:
        class: %fos_facebook.user.login.class%
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"

    procergs.hwi_twitter.user_provider:
        class: %procergs.hwi_twitter.user_provider.class%
        arguments: [ "@fos_user.user_manager", { twitter: twitterId } ]

    procergs_person.registration.form.type:
        class: %procergs_person.registration.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_registration }

    procergs_person.profile.form.type:
        class: %procergs_person.profile.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_profile }

    procergs_person.resetting.form.type:
        class: %procergs_person.resetting.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_resetting }

    procergs_logincidadao.user_provider:
        class: %procergs_logincidadao.user_provider.class%
        arguments: ["@fos_user.user_manager"]

    procergs_logincidadao.user_manager:
        class: %procergs_logincidadao.user_manager.class%
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager"]
