parameters:
    procergs.hwi_twitter.user_provider.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\FOSUBUserProvider

services:
    fos_facebook.user.login:
        class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"

    procergs.hwi_twitter.user_provider:
        class: %procergs.hwi_twitter.user_provider.class%
        arguments: [ "@fos_user.user_manager", { twitter: twitterId } ]

    procergs_person.registration.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_registration }

    procergs_person.profile.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_profile }

    procergs_logincidadao.user_provider:
        class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\LoginCidadaoProvider
        arguments: ["@fos_user.user_manager"]
