parameters:
    oidc.person.serialize.listenner.class: LoginCidadao\OpenIDBundle\EventListenner\PersonSerializeEventListenner
    oidc.storage.session_state.class: LoginCidadao\OpenIDBundle\Storage\SessionState

    oauth2.storage.authorization_code.class: LoginCidadao\OpenIDBundle\Storage\AuthorizationCode
    oauth2.storage.client_credentials.class: LoginCidadao\OpenIDBundle\Storage\ClientCredentials
    oauth2.storage.refresh_token.class: LoginCidadao\OpenIDBundle\Storage\RefreshToken
    oauth2.storage.access_token.class: LoginCidadao\OpenIDBundle\Storage\AccessToken

    oauth2.grant_type.authorization_code.class: LoginCidadao\OpenIDBundle\GrantType\AuthorizationCode

    oauth2.storage.user_claims.class: LoginCidadao\OpenIDBundle\Storage\UserClaims
    oauth2.storage.public_key.class: LoginCidadao\OpenIDBundle\Storage\PublicKey

    oauth2.scope_manager.class: LoginCidadao\OpenIDBundle\Manager\ScopeManager

    oauth2.server.config:
        use_openid_connect: true
        issuer: %jwt_iss%
        allow_implicit: true

services:
    oauth2.storage.user_claims:
        class: %oauth2.storage.user_claims.class%
        arguments: [ @doctrine.orm.entity_manager ]

    oauth2.storage.public_key:
        class: %oauth2.storage.public_key.class%
        arguments: [ @doctrine.orm.entity_manager ]

    oidc.storage.session_state:
        class: %oidc.storage.session_state.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @security.token_storage
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    oidc.person.serialize.listenner:
        class: %oidc.person.serialize.listenner.class%
        arguments:
            - @lc_accesstoken_manager
            - %secret%
        tags:
            - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize }
