procergso_auth_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PROCERGSOAuthBundle:Default:index }

procergs_oauth_init:
    pattern: /initClient
    defaults: { _controller: PROCERGSOAuthBundle:Client:initClient }
    
procergs_oauth_getid:
    pattern: /getPub/{id}
    defaults: { _controller: PROCERGSOAuthBundle:Client:getPublicId }