services:
    procergs_phone_verification.events.subscriber:
        class: PROCERGS\LoginCidadao\PhoneVerificationBundle\Event\PhoneVerificationSubscriber
        arguments:
            - "@sms"
            - "@translator"
            - "@router"
            - "@procergs_phone_verification.circuit_breaker.sms"
        calls:
            - ['setLogger', ["@?logger"]]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phone_verification }

    procergs_phone_verification.circuit_breaker.sms:
        class: Eljam\CircuitBreaker\Breaker
        arguments:
            - "phone_verification.sms"
            - { max_failure: 3, reset_timeout: 10 }
            - "@cache"
            - null
            - "@event_dispatcher"
