procergs_login_cidadao_notification:
    resource: "@LoginCidadaoNotificationBundle/Controller/"
    type:     annotation
    prefix:   /

procergs_login_cidadao_notification_jsapi:
    resource: "@LoginCidadaoNotificationBundle/Controller/JsAPI/NotificationController.php"
    prefix:   /jsapi/v1
    type: rest
    defaults: { _format: json }
